// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type MaritalStatus string

const (
	MaritalStatusSingle     MaritalStatus = "single"
	MaritalStatusMarried    MaritalStatus = "married"
	MaritalStatusDivorced   MaritalStatus = "divorced"
	MaritalStatusWidowed    MaritalStatus = "widowed"
	MaritalStatusLegalUnion MaritalStatus = "legal_union"
)

func (e *MaritalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaritalStatus(s)
	case string:
		*e = MaritalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaritalStatus: %T", src)
	}
	return nil
}

type NullMaritalStatus struct {
	MaritalStatus MaritalStatus `json:"marital_status"`
	Valid         bool          `json:"valid"` // Valid is true if MaritalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaritalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaritalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaritalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaritalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaritalStatus), nil
}

type Company struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	TaxID     string         `json:"tax_id"`
	Industry  sql.NullString `json:"industry"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type CompanyCustomer struct {
	CompanyID  int32        `json:"company_id"`
	CustomerID int32        `json:"customer_id"`
	JoinedAt   sql.NullTime `json:"joined_at"`
}

type Customer struct {
	ID            int32             `json:"id"`
	FirstName     string            `json:"first_name"`
	LastName      string            `json:"last_name"`
	Birthday      time.Time         `json:"birthday"`
	Address       sql.NullString    `json:"address"`
	MaritalStatus NullMaritalStatus `json:"marital_status"`
	Occupation    sql.NullString    `json:"occupation"`
	IDNumber      string            `json:"id_number"`
	CreatedAt     sql.NullTime      `json:"created_at"`
}

type CustomerDocument struct {
	CustomerID int32 `json:"customer_id"`
	DocumentID int32 `json:"document_id"`
}

type Document struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	SizeBytes int64        `json:"size_bytes"`
	FilePath  string       `json:"file_path"`
	CreatedAt sql.NullTime `json:"created_at"`
}
