// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sidebar(activePage string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<aside class=\"fixed left-0 top-0 h-screen w-sidebar_width bg-surface-container-lowest border-r border-outline-variant flex flex-col py-lg z-50\"><div class=\"px-lg mb-2xl\"><h1 class=\"font-headline-md text-headline-md font-bold text-primary mb-xs\">Themis Legal</h1><p class=\"font-label-sm text-label-sm text-secondary\">Legal Management</p></div><button class=\"mx-lg mb-xl bg-primary text-on-primary font-body-md font-bold py-md px-lg flex items-center justify-center gap-sm transition-opacity hover:opacity-90\"><span class=\"material-symbols-outlined\">add</span> New Case</button><nav class=\"flex-1 space-y-unit\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if activePage == "customers" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a class=\"flex items-center gap-md px-lg py-md text-primary font-bold border-l-4 border-primary bg-surface-container-low transition-colors duration-200\" href=\"/customers\"><span class=\"material-symbols-outlined\">group</span> <span>Customers</span></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a class=\"flex items-center gap-md px-lg py-md text-secondary font-medium hover:bg-surface-container transition-colors duration-200\" href=\"/customers\"><span class=\"material-symbols-outlined\">group</span> <span>Customers</span></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if activePage == "documents" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a class=\"flex items-center gap-md px-lg py-md text-primary font-bold border-l-4 border-primary bg-surface-container-low transition-colors duration-200\" href=\"/documents/builder\"><span class=\"material-symbols-outlined\">description</span> <span>Documents</span></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<a class=\"flex items-center gap-md px-lg py-md text-secondary font-medium hover:bg-surface-container transition-colors duration-200\" href=\"/documents/builder\"><span class=\"material-symbols-outlined\">description</span> <span>Documents</span></a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<a class=\"flex items-center gap-md px-lg py-md text-secondary font-medium hover:bg-surface-container transition-colors duration-200\" href=\"#\"><span class=\"material-symbols-outlined\">edit_note</span> <span>Drafts</span></a></nav><div class=\"mt-auto pt-lg border-t border-outline-variant/30 space-y-unit\"><a class=\"flex items-center gap-md px-lg py-md text-secondary font-medium hover:bg-surface-container transition-colors duration-200\" href=\"#\"><span class=\"material-symbols-outlined\">settings</span> <span>Settings</span></a> <a class=\"flex items-center gap-md px-lg py-md text-secondary font-medium hover:bg-surface-container transition-colors duration-200\" href=\"#\"><span class=\"material-symbols-outlined\">help</span> <span>Support</span></a></div></aside>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
