// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TopNav(searchPlaceholder string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"flex justify-between items-center h-16 px-xl bg-surface z-40 sticky top-0 border-b border-outline-variant/30\"><div class=\"flex items-center flex-1 max-w-2xl\"><div class=\"relative w-full max-w-xs\"><span class=\"material-symbols-outlined absolute left-md top-1/2 -translate-y-1/2 text-outline text-[20px]\">search</span> <input class=\"w-full pl-3xl pr-md py-sm bg-surface-container-lowest border border-outline-variant focus:border-primary focus:ring-0 text-body-md transition-all\" placeholder=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(searchPlaceholder)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/topnav.templ`, Line: 10, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" type=\"text\"></div></div><div class=\"flex items-center gap-lg ml-xl\"><nav class=\"flex gap-lg font-label-sm text-label-sm\"><a class=\"text-on-surface-variant hover:text-primary transition-all\" href=\"#\">Dashboard</a> <a class=\"text-on-surface-variant hover:text-primary transition-all\" href=\"#\">Reports</a></nav><div class=\"h-6 w-[1px] bg-outline-variant\"></div><div class=\"flex items-center gap-md\"><button class=\"text-on-surface-variant hover:text-primary transition-all active:scale-90\"><span class=\"material-symbols-outlined\">notifications</span></button> <button class=\"text-on-surface-variant hover:text-primary transition-all active:scale-90\"><span class=\"material-symbols-outlined\">history</span></button><div class=\"w-8 h-8 rounded-full bg-primary-container text-on-primary-container flex items-center justify-center font-bold text-[13px]\">AS</div></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
