// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/marti700/themis/backend/database"
	"github.com/marti700/themis/frontend/components"
)

func initials(c database.Customer) string {
	f := ""
	l := ""
	if len(c.FirstName) > 0 {
		f = string([]rune(c.FirstName)[0:1])
	}
	if len(c.LastName) > 0 {
		l = string([]rune(c.LastName)[0:1])
	}
	return f + l
}

var avatarColors = []string{
	"bg-secondary-container text-on-secondary-container",
	"bg-primary-container text-on-primary-container",
	"bg-tertiary-fixed text-on-tertiary-fixed-variant",
	"bg-secondary-fixed text-on-secondary-fixed-variant",
	"bg-surface-container-high text-on-surface-variant",
}

func avatarColor(id int32) string {
	return avatarColors[int(id)%len(avatarColors)]
}

func Directory(customers []database.Customer) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = components.Sidebar("customers").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <main class=\"ml-sidebar_width min-h-screen\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.TopNav("Search by name, ID, or role...").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"p-xl\"><div class=\"mb-lg flex justify-between items-end\"><div><h2 class=\"font-headline-lg text-headline-lg text-primary mb-xs\">Customer Directory</h2><p class=\"font-body-md text-secondary\">Manage and view all registered legal clients within the system.</p></div><div class=\"flex gap-sm\"><button class=\"px-md py-sm border border-outline-variant bg-surface-container-lowest flex items-center gap-xs font-label-sm text-secondary hover:bg-surface-container transition-colors\"><span class=\"material-symbols-outlined text-[18px]\">filter_list</span> Filter</button> <button class=\"px-md py-sm border border-outline-variant bg-surface-container-lowest flex items-center gap-xs font-label-sm text-secondary hover:bg-surface-container transition-colors\"><span class=\"material-symbols-outlined text-[18px]\">download</span> Export</button></div></div><!-- Customer Table --><div class=\"bg-surface-container-lowest border border-outline-variant shadow-[0px_4px_12px_rgba(0,0,0,0.03)] overflow-hidden\"><table class=\"w-full text-left border-collapse\"><thead class=\"bg-surface-container-low border-b border-outline-variant\"><tr><th class=\"px-lg py-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider\">Name</th><th class=\"px-lg py-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider\">Document ID</th><th class=\"px-lg py-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider\">Occupation</th><th class=\"px-lg py-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider\">Status</th><th class=\"px-lg py-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider text-right\">Actions</th></tr></thead> <tbody class=\"divide-y divide-outline-variant\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, c := range customers {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<tr class=\"hover:bg-surface-container-low transition-colors\"><td class=\"px-lg py-md\"><div class=\"flex items-center gap-md\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 = []any{"w-10 h-10 flex items-center justify-center font-bold font-body-md", avatarColor(c.ID)}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var3).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(initials(c))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 73, Col: 25}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div><div><p class=\"font-body-md font-bold text-primary\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(c.FirstName)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 76, Col: 72}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(c.LastName)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 76, Col: 87}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</p><p class=\"text-[12px] text-secondary\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(c.IDNumber)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 77, Col: 62}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</p></div></div></td><td class=\"px-lg py-md font-mono text-body-md text-on-surface-variant\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var9 string
				templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(c.IDNumber)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 81, Col: 92}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</td><td class=\"px-lg py-md font-body-md text-on-surface-variant\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if c.Occupation.Valid {
					var templ_7745c5c3_Var10 string
					templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(c.Occupation.String)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 84, Col: 32}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "—")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</td><td class=\"px-lg py-md\"><span class=\"inline-flex items-center gap-xs px-sm py-[2px] bg-secondary-container text-on-secondary-container text-[11px] font-bold uppercase rounded-full\"><span class=\"w-1.5 h-1.5 rounded-full bg-on-secondary-container\"></span> Active</span></td><td class=\"px-lg py-md text-right\"><a href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var11 templ.SafeURL
				templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(fmt.Sprintf("/customers/%d/profile", c.ID)))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 96, Col: 77}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" class=\"text-primary font-label-sm hover:underline flex items-center gap-xs ml-auto\">View <span class=\"material-symbols-outlined text-[18px]\">chevron_right</span></a></td></tr>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</tbody></table><div class=\"bg-surface-container px-lg py-md flex justify-between items-center\"><p class=\"font-label-sm text-secondary\">Showing ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", len(customers)))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 106, Col: 50}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, " customers</p><div class=\"flex gap-xs\"><button class=\"w-8 h-8 flex items-center justify-center border border-outline-variant bg-surface-container-lowest text-secondary disabled:opacity-50\" disabled><span class=\"material-symbols-outlined text-[18px]\">keyboard_arrow_left</span></button> <button class=\"w-8 h-8 flex items-center justify-center border border-primary bg-primary text-on-primary font-bold text-[12px]\">1</button> <button class=\"w-8 h-8 flex items-center justify-center border border-outline-variant bg-surface-container-lowest text-secondary\"><span class=\"material-symbols-outlined text-[18px]\">keyboard_arrow_right</span></button></div></div></div><!-- Dashboard Summary Widgets --><div class=\"mt-2xl grid grid-cols-12 gap-lg\"><div class=\"col-span-8 bg-surface-container-low p-lg border border-outline-variant/50\"><div class=\"flex justify-between items-start mb-md\"><h3 class=\"font-headline-md text-headline-md text-primary\">Registration Insights</h3><span class=\"text-[11px] font-bold text-secondary uppercase tracking-widest\">Last 30 Days</span></div><div class=\"flex items-end gap-sm h-32\"><div class=\"flex-1 bg-primary/20 h-[40%]\"></div><div class=\"flex-1 bg-primary/20 h-[60%]\"></div><div class=\"flex-1 bg-primary h-[85%]\"></div><div class=\"flex-1 bg-primary/20 h-[45%]\"></div><div class=\"flex-1 bg-primary/40 h-[70%]\"></div></div><div class=\"mt-md pt-md border-t border-outline-variant flex gap-xl\"><div><p class=\"text-[24px] font-bold text-primary\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", len(customers)))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 135, Col: 89}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</p><p class=\"font-label-sm text-secondary\">Total Customers</p></div><div><p class=\"text-[24px] font-bold text-primary\">92%</p><p class=\"font-label-sm text-secondary\">Completion Rate</p></div></div></div><div class=\"col-span-4 bg-tertiary text-on-tertiary p-lg flex flex-col justify-between\"><div><span class=\"material-symbols-outlined text-on-tertiary-container mb-md\">verified_user</span><h3 class=\"font-headline-md text-headline-md mb-xs\">Legal Compliance</h3><p class=\"font-label-sm text-on-tertiary-container\">Verification status across current customer directory.</p></div><div class=\"mt-xl\"><div class=\"w-full bg-on-tertiary-fixed h-2 mb-xs\"><div class=\"bg-primary-fixed h-full w-[88%]\"></div></div><p class=\"font-label-sm text-on-tertiary-container flex justify-between\"><span>88% Verified</span> <span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var14 string
			templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", len(customers)))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/pages/directory.templ`, Line: 156, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, " Total</span></p></div></div></div></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout("Customer Directory").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
