// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Gender string

const (
	GenderFemenin  Gender = "femenin"
	GenderMasculin Gender = "masculin"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type MaritalStatus string

const (
	MaritalStatusSingle     MaritalStatus = "single"
	MaritalStatusMarried    MaritalStatus = "married"
	MaritalStatusDivorced   MaritalStatus = "divorced"
	MaritalStatusWidowed    MaritalStatus = "widowed"
	MaritalStatusLegalUnion MaritalStatus = "legal_union"
)

func (e *MaritalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaritalStatus(s)
	case string:
		*e = MaritalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaritalStatus: %T", src)
	}
	return nil
}

type NullMaritalStatus struct {
	MaritalStatus MaritalStatus `json:"marital_status"`
	Valid         bool          `json:"valid"` // Valid is true if MaritalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaritalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaritalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaritalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaritalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaritalStatus), nil
}

type Company struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	TaxID     string             `json:"tax_id"`
	Industry  pgtype.Text        `json:"industry"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CompanyCustomer struct {
	CompanyID  int32              `json:"company_id"`
	CustomerID int32              `json:"customer_id"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
}

type Customer struct {
	ID            int32              `json:"id"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Birthday      pgtype.Date        `json:"birthday"`
	Address       pgtype.Text        `json:"address"`
	MaritalStatus NullMaritalStatus  `json:"marital_status"`
	Occupation    pgtype.Text        `json:"occupation"`
	IDNumber      string             `json:"id_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Gender        NullGender         `json:"gender"`
	Nationality   pgtype.Text        `json:"nationality"`
}

type CustomerDocument struct {
	CustomerID int32 `json:"customer_id"`
	DocumentID int32 `json:"document_id"`
}

type Document struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	SizeBytes int64              `json:"size_bytes"`
	FilePath  string             `json:"file_path"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
