// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCustomerToCompany = `-- name: AddCustomerToCompany :exec
INSERT INTO company_customers (company_id, customer_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCustomerToCompanyParams struct {
	CompanyID  int32 `json:"company_id"`
	CustomerID int32 `json:"customer_id"`
}

func (q *Queries) AddCustomerToCompany(ctx context.Context, arg *AddCustomerToCompanyParams) error {
	_, err := q.db.Exec(ctx, addCustomerToCompany, arg.CompanyID, arg.CustomerID)
	return err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    first_name, last_name, birthday, address, marital_status, occupation, id_number
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, first_name, last_name, birthday, address, marital_status, occupation, id_number, created_at
`

type CreateCustomerParams struct {
	FirstName     string            `json:"first_name"`
	LastName      string            `json:"last_name"`
	Birthday      pgtype.Date       `json:"birthday"`
	Address       pgtype.Text       `json:"address"`
	MaritalStatus NullMaritalStatus `json:"marital_status"`
	Occupation    pgtype.Text       `json:"occupation"`
	IDNumber      string            `json:"id_number"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg *CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.FirstName,
		arg.LastName,
		arg.Birthday,
		arg.Address,
		arg.MaritalStatus,
		arg.Occupation,
		arg.IDNumber,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Birthday,
		&i.Address,
		&i.MaritalStatus,
		&i.Occupation,
		&i.IDNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getCompaniesByCustomer = `-- name: GetCompaniesByCustomer :many
SELECT co.id, co.name, co.tax_id, co.industry, co.created_at FROM companies co
JOIN company_customers cc ON co.id = cc.company_id
WHERE cc.customer_id = $1
`

func (q *Queries) GetCompaniesByCustomer(ctx context.Context, customerID int32) ([]Company, error) {
	rows, err := q.db.Query(ctx, getCompaniesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TaxID,
			&i.Industry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, first_name, last_name, birthday, address, marital_status, occupation, id_number, created_at FROM customers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Birthday,
		&i.Address,
		&i.MaritalStatus,
		&i.Occupation,
		&i.IDNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomersByCompany = `-- name: GetCustomersByCompany :many
SELECT c.id, c.first_name, c.last_name, c.birthday, c.address, c.marital_status, c.occupation, c.id_number, c.created_at FROM customers c
JOIN company_customers cc ON c.id = cc.customer_id
WHERE cc.company_id = $1
`

func (q *Queries) GetCustomersByCompany(ctx context.Context, companyID int32) ([]Customer, error) {
	rows, err := q.db.Query(ctx, getCustomersByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Birthday,
			&i.Address,
			&i.MaritalStatus,
			&i.Occupation,
			&i.IDNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsByCustomer = `-- name: GetDocumentsByCustomer :many
SELECT d.id, d.name, d.size_bytes, d.file_path, d.created_at FROM documents d
JOIN customer_documents cd ON d.id = cd.document_id
WHERE cd.customer_id = $1
`

func (q *Queries) GetDocumentsByCustomer(ctx context.Context, customerID int32) ([]Document, error) {
	rows, err := q.db.Query(ctx, getDocumentsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SizeBytes,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkDocumentToCustomer = `-- name: LinkDocumentToCustomer :exec
INSERT INTO customer_documents (customer_id, document_id)
VALUES ($1, $2)
`

type LinkDocumentToCustomerParams struct {
	CustomerID int32 `json:"customer_id"`
	DocumentID int32 `json:"document_id"`
}

func (q *Queries) LinkDocumentToCustomer(ctx context.Context, arg *LinkDocumentToCustomerParams) error {
	_, err := q.db.Exec(ctx, linkDocumentToCustomer, arg.CustomerID, arg.DocumentID)
	return err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, first_name, last_name, birthday, address, marital_status, occupation, id_number, created_at FROM customers ORDER BY last_name, first_name
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Birthday,
			&i.Address,
			&i.MaritalStatus,
			&i.Occupation,
			&i.IDNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
